name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Google Cloud VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.GC_VM_IP }}
        username: ${{ secrets.GC_VM_USER }}
        key: ${{ secrets.GC_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/ton-projet
          git pull origin main
          npm install # ou autre commande pour ton projet
          pm2 restart all
